2017-03-02T07:39:41.020Z - error: uncaughtException: cb is not a function date=Thu Mar 02 2017 01:39:41 GMT-0600 (CST), pid=39529, uid=501, gid=20, cwd=/Users/zmz0305/workspace/OneDrive/workplace/relink/chat_service/tests, execPath=/Users/zmz0305/.nvm/versions/node/v6.9.5/bin/node, version=v6.9.5, argv=[/Users/zmz0305/.nvm/versions/node/v6.9.5/bin/node, /Users/zmz0305/workspace/OneDrive/workplace/relink/chat_service/tests/try.js], rss=43319296, heapTotal=32542720, heapUsed=14374712, loadavg=[1.69775390625, 1.5634765625, 1.630859375], uptime=733606, trace=[column=9, file=/Users/zmz0305/workspace/OneDrive/workplace/relink/chat_service/database/room_apis.js, function=Object.module.exports.joinRoom, line=81, method=module.exports.joinRoom, native=false, column=11, file=/Users/zmz0305/workspace/OneDrive/workplace/relink/chat_service/tests/try.js, function=, line=25, method=null, native=false, column=32, file=module.js, function=Module._compile, line=570, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=579, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=487, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=446, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=438, method=Module._load, native=false, column=10, file=module.js, function=Module.runMain, line=604, method=runMain, native=false, column=7, file=bootstrap_node.js, function=run, line=394, method=null, native=false, column=9, file=bootstrap_node.js, function=startup, line=149, method=null, native=false, column=3, file=bootstrap_node.js, function=null, line=509, method=null, native=false], stack=[TypeError: cb is not a function,     at Object.module.exports.joinRoom (/Users/zmz0305/workspace/OneDrive/workplace/relink/chat_service/database/room_apis.js:81:9),     at Object.<anonymous> (/Users/zmz0305/workspace/OneDrive/workplace/relink/chat_service/tests/try.js:25:11),     at Module._compile (module.js:570:32),     at Object.Module._extensions..js (module.js:579:10),     at Module.load (module.js:487:32),     at tryModuleLoad (module.js:446:12),     at Function.Module._load (module.js:438:3),     at Module.runMain (module.js:604:10),     at run (bootstrap_node.js:394:7),     at startup (bootstrap_node.js:149:9),     at bootstrap_node.js:509:3]
2017-03-04T22:18:46.686Z - error: uncaughtException: failed to connect to server [127.0.0.1:27017] on first connect date=Sat Mar 04 2017 16:18:46 GMT-0600 (CST), pid=53610, uid=501, gid=20, cwd=/Users/zmz0305/workspace/OneDrive/workplace/relink/chat_service, execPath=/Users/zmz0305/.nvm/versions/node/v6.9.5/bin/node, version=v6.9.5, argv=[/Users/zmz0305/.nvm/versions/node/v6.9.5/bin/node, /Users/zmz0305/workspace/OneDrive/workplace/relink/chat_service/app.js], rss=57544704, heapTotal=38834176, heapUsed=22580592, loadavg=[1.78125, 1.87255859375, 1.896484375], uptime=959151, trace=[column=35, file=/Users/zmz0305/workspace/OneDrive/workplace/relink/chat_service/node_modules/mongodb-core/lib/topologies/server.js, function=, line=326, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=/Users/zmz0305/workspace/OneDrive/workplace/relink/chat_service/node_modules/mongodb-core/lib/connection/pool.js, function=, line=270, method=null, native=false, column=16, file=events.js, function=Connection.g, line=291, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=49, file=/Users/zmz0305/workspace/OneDrive/workplace/relink/chat_service/node_modules/mongodb-core/lib/connection/connection.js, function=, line=175, method=null, native=false, column=16, file=events.js, function=Socket.g, line=291, method=g, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=8, file=net.js, function=emitErrorNT, line=1278, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[MongoError: failed to connect to server [127.0.0.1:27017] on first connect,     at Pool.<anonymous> (/Users/zmz0305/workspace/OneDrive/workplace/relink/chat_service/node_modules/mongodb-core/lib/topologies/server.js:326:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (/Users/zmz0305/workspace/OneDrive/workplace/relink/chat_service/node_modules/mongodb-core/lib/connection/pool.js:270:12),     at Connection.g (events.js:291:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (/Users/zmz0305/workspace/OneDrive/workplace/relink/chat_service/node_modules/mongodb-core/lib/connection/connection.js:175:49),     at Socket.g (events.js:291:16),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at emitErrorNT (net.js:1278:8),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickCallback (internal/process/next_tick.js:98:9)]
